version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    versioning-strategy: 'increase'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    ignore:
      - dependency-name: '@salesforce/dev-scripts'
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
