version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '06:00'
      timezone: 'Europe/Berlin'
    versioning-strategy: 'increase'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
