version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '22:00'
      timezone: 'Europe/Berlin'
    versioning-strategy: 'increase'
    cooldown:
      exclude:
        - '@salesforce/source-deploy-retrieve'
        - '@salesforce/source-tracking'
        - 'isomorphic-git'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 50
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '22:00'
      timezone: 'Europe/Berlin'
