name: Close Stale Issues
permissions:
  issues: write
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-label: stale
          days-before-issue-stale: 7
          stale-issue-message: 'This issue has not received a response in 7 days. It will auto-close in 7 days unless a response is posted.'
          exempt-issue-labels: bug,enhancement
          any-of-labels: more information required
