# runs some very-large-repo tests (for windows filesystem limits) and commits perf results for comparison
name: perf-scale-nuts
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

# linux will finish 10 min ahead of windows, but prevent other branches/commits from hitting simultaneously
# since we're pushing git commits and there would be conflicts
concurrency: perf-scale-nuts

jobs:
  perf-scale-nuts:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - run: git config --system core.longpaths true
        if: ${{ runner.os == 'Windows' }}

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn
      - uses: salesforcecli/github-workflows/.github/actions/yarnInstallWithRetries@main
        with:
          ignore-scripts: true
      - run: |
          yarn mocha test/nuts/scale/eda.nut.ts --timeout 500000

      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@d48d326b4ca9ba73ca0cd0d59f108f9e02a381c7
        with:
          tool: 'customSmallerIsBetter'
          output-file-path: test/nuts/scale/output.json
          comment-on-alert: true
          fail-on-alert: true
          # Push and deploy GitHub pages branch automatically
          # this has a bug where it creates duplicate commits when summary-always and aut-push are both true
          # summary-always: true
          comment-always: true
          benchmark-data-dir-path: perf-${{ runner.os}}
          auto-push: true
          github-token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
