name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    uses: jayree/github-workflows/.github/workflows/unitTest.yml@jayree
  nuts:
    needs: unit-tests
    uses: jayree/github-workflows/.github/workflows/nut.yml@jayree
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    with:
      os: ${{ matrix.os }}
