name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  nuts:
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
    secrets: inherit
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    with:
      os: ${{ matrix.os }}
